require 'active_record'

desc 'Migrate to utf8mb4'
task :migrate_to_utf8mb4 => :environment do
  ActiveRecord::Base.transaction do
    ActiveRecord::Base.connection.execute("ALTER TABLE attachments CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE auth_sources CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE boards CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE changes CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE changeset_parents CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE changesets CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE changesets_issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE comments CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE contingency_ratios CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_field_enumerations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_fields CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_fields_projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_fields_roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_fields_trackers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE custom_values CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE documents CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE email_addresses CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE enabled_modules CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE enumerations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE groups_users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE import_items CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE imports CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE issue_categories CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE issue_relations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE issue_statuses CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE issues CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE journal_details CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE journals CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE member_roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE members CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE messages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE news CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE open_id_authentication_associations CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE open_id_authentication_nonces CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE projects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE projects_trackers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE queries CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE queries_roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE repositories CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE roles_managed_roles CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE settings CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE time_entries CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE tokens CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE trackers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE user_preferences CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE users CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE versions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE watchers CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE wiki_content_versions CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE wiki_contents CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE wiki_pages CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE wiki_redirects CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE wikis CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    ActiveRecord::Base.connection.execute("ALTER TABLE workflows CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
  end
end
